# genesis dna — adaptive seeds for the data spine
symbol: "XAUUSD"

modes:
  sim:
    # mac-friendly: use OANDA practice + your TradingView local bridge
    sources:
      - type: "oanda"
        account: "practice" # or "live"
        stream_url: "https://stream-fxpractice.oanda.com/v3/accounts/{ACCOUNT_ID}/pricing/stream"
        rest_url: "https://api-fxpractice.oanda.com/v3"
        account_id: "REPLACE_ME"
        token_env: "OANDA_TOKEN" # read from env var
        instruments: ["XAU_USD"]
      - type: "tv_bridge"
        ws_url: "ws://127.0.0.1:8765" # your local TV/OHLC bridge (you control it)
        channels: ["orderbook", "trades", "quotes"]
  live:
    # windows + MT5/brokers
    sources:
      - type: "mt5"
        symbol: "XAUUSD"
        poll_ms: 150 # adaptive; initial seed only
      - type: "oanda"
        account: "live"
        stream_url: "https://stream-fxtrade.oanda.com/v3/accounts/{ACCOUNT_ID}/pricing/stream"
        rest_url: "https://api-fxtrade.oanda.com/v3"
        account_id: "REPLACE_ME"
        token_env: "OANDA_TOKEN"
        instruments: ["XAU_USD"]

adaptive:
  qos:
    max_timestamp_delay_ms: 50 # drop events if older than this (present-only discipline)
    max_jitter_ms: 25 # triggers resample/adapt if exceeded
    heartbeat_ms: 500 # expected keepalive cadence per source
    backoff:
      min_ms: 250
      max_ms: 4000
      factor: 2.0
  sampling:
    base_hz: 10 # initial; will adapt with vol/jitter
    min_hz: 2
    max_hz: 50
  fuse:
    prefer_depth_levels: 10 # min L2 depth to accept as “rich” book
    dedupe_horizon_ms: 20 # collapse near-dup ticks
    clock_sync_slack_ms: 15 # tolerance across venues

telemetry:
  log_level: "INFO"
  emit_book: true
  emit_trades: true
  emit_quotes: true
